### PR TITLE
Do not error if public_ip == ''

### PR DESCRIPTION
**Pull request by ryanlovett**
Despite the traitlet default of 0.0.0.0, if I don't append `--NCHPApp.public_ip=0.0.0.0` to c.JupyterHub.proxy_cmd, the nginx config will have `listen :<myport> ssl;` which will cause nginx to error with

```
no host in ":<myport>" of the "listen" directive in /tmp/...
```

I can workaround this with the patch so that the listen line becomes `listen <myport> ssl;` which is fine in this instance. The real problem is that public_ip is getting overridden I guess, but I'm not sure how.

### CODE REVIEW

**Comment by yuvipanda** [comment]
I think it's because if jupyterhub is starting it, and it sets ip to ''. I've pushed a PR to fix it at https://github.com/jupyterhub/jupyterhub/pull/740

**Comment by yuvipanda** [comment]
We can also work around this in nchp, but should put it in app.py rather than the jinja template.

**Comment by yuvipanda** [comment]
Intermediate workaround is to set:

```
c.JupyterHub.ip = '0.0.0.0'
```

in your jupyterhub_config.py file

**Comment by yuvipanda** [comment]
@ryanlovett can you try https://github.com/yuvipanda/jupyterhub-nginx-chp/pull/8

**Comment by ryanlovett** [comment]
The patch worked! (modulo a small syntax issue) The host is no longer empty.

**Pull request closed without merging**
