### PR TITLE
Seed public_port to proxy header

### PR DESCRIPTION
**Pull request by ryanlovett**
When running the proxy on a non-standard port (8443), when a user shut down their server the hub trips over a [CORS check](https://github.com/jupyterhub/jupyterhub/blob/c9ae45bef3ddda8e5b0322d34f7e9d331650111e/jupyterhub/apihandlers/base.py#L38) with the error

`Blocking Cross Origin API request.  Referer: https://myserver:8443/hub/home, Host: myserver/hub/`

### CODE REVIEW

**Comment by yuvipanda** [comment]
I remember running into issues with this earlier - I had originally included it, but removed it with cdf93c984ee06ec99e1d594ccea856598cc19c83. I agree it makes sense to include it, but I was running into issues with this when testing. I'll try this out again!

**Comment by yuvipanda** [comment]
on a bit more digging, the problem that manifested itself happens in the following case:

user -> edge proxy (listens on port 80) -> nchp (listens on port 8080) -> jupyter singleuser notebooks.

In this case, the Origin header from the client side js will be set to hostname:80 (since that's the edge proxy's port, and that's what the user connects to), while Hostname will be set to 8080 (since that's what nchp is listening on!).

So the proper fix would be to find a way of making sure that the Host header that gets passed to the notebook matches what the _user_ sees, rather than what the proxy is bound to. Multi host http proxying is fun :8ball: 

I feel like this definitely needs _some_ diagramming at least to figure out the proper solution.

**Comment by yuvipanda** [comment]
@ryanlovett can you check out #7?

**Comment by ryanlovett** [comment]
Works for me!

**Comment by yuvipanda** [comment]
Ok, I'm going to close this one then. Thanks a lot for reporting and testing this through!

**Pull request closed without merging**
